import { Inter } from "next/font/google";
import "./globals.css";
import "../styles/index.scss";
import SiteHeader from "../components/SiteHeader/SiteHeader";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en " className="bg-neutral-50">
<head>
<Script
id='gtm'
dangerouslySetInnerHTML={{
  __html:`


!function (w, d, t) {
  w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie","holdConsent","revokeConsent","grantConsent"],ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(
var e=ttq._i[t]||[],n=0;n<ttq.methods.length;n++)ttq.setAndDefer(e,ttq.methods[n]);return e},ttq.load=function(e,n){var r="https://analytics.tiktok.com/i18n/pixel/events.js",o=n&&n.partner;ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=r,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=n||{};n=document.createElement("script")
;n.type="text/javascript",n.async=!0,n.src=r+"?sdkid="+e+"&lib="+t;e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(n,e)};


  ttq.load('CQS65KJC77U5SJ4PVHM0');
  ttq.page();
}(window, document, 'ttq');


  `
}}
>
</Script>
    </head>

      <body className={inter.className}>
        <UserProvider>
        <SiteHeader/>
          {children}
          </UserProvider>
        </body>
    </html>
  );
}
